name: twiine
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1
  font_awesome_flutter: ^8.8.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # authentication stuff
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.16.1
  flutter_webview_plugin: ^0.3.10+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  cloud_functions: ^0.5.0

  #For the search bar
  flappy_search_bar: 1.4.1

  #validation for forms
  validators: ^2.0.1

  # svgs
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: lib/fonts/facebook.ttf
    - family: Karla
      fonts: 
        - asset: lib/fonts/Karla-Regular.ttf
        - asset: lib/fonts/Karla-Bold.ttf
        - asset: lib/fonts/Karla-Italic.ttf
        - asset: lib/fonts/Karla-BoldItalic.ttf
    - family: Acumin Pro
      fonts: 
        - asset: lib/fonts/Acumin-BdItPro.otf
        - asset: lib/fonts/Acumin-BdPro.otf
        - asset: lib/fonts/Acumin-ItPro.otf
        - asset: lib/fonts/Acumin-RPro.otf
